# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SmartIndia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartIndia

  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'MaterialControls'
  pod 'ObjectMapper'
  pod 'MaterialKit', :git => 'https://github.com/faresbh/MaterialKit',:branch => "swift3"

end
